
version: 2

models:
  - name: fact_bording_passes
    columns:
      - name: ticket_no
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: fact_flights
    columns:
      - name: flight_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: fact_tickets
    columns:
      - name: book_ref
        description: "The primary key for this table"
        tests:
          - unique
          - not_null